version: '3.3'

services:
  backend:
    build: ./backend
    expose:
     - 8000
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code/backend
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
  ui:
    build: ./ui
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./ui/src/:/code/ui/src
      - ./ui/public/:/code/ui/public
    links:
      - "backend:backend"