name: Test-style-check

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        sudo pip install pycodestyle
        pip install pdoc
        pip install pytest-html
    - name: Test all
      run: |
        pdoc --html --only-pypath --html-dir=./docs
        pycodestyle --first backend/tests.py
#     - name: Code Coverage
#       run: |
#         python -m pip install coverage
#         pip install coverage-badge
#         python -m coverage run -m backend.app
#         python -m coverage report 
#         # coverage-badge -o coverage.svg	        
#         # percent=$(tail -1 coverage_report.txt | awk '{print $(NF)}')
#         # echo "Code coverage = $percent"
    - name: CodeCov
      uses: codecov/codecov-action@v3
